Payroll and payslip page
torodeveloper/payroll-system-bellini-app pull request #2
Opened 2024-04-17 07:06 UTC by kaedm

1. Payroll page, displays the payrolls of each group, you can also run payroll here
![1Screenshot_2024-04-17_15-02-31](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/fb992c1a-1910-4bca-92e7-dd66344da37a)

2. Run payroll modal in the payroll page, Here you can select the Paygroup, Runtype, Start date, End date and Check date of the payroll you want to create
![11Screenshot_2024-04-17_15-03-09](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/a4a50b87-5b29-49fa-95d1-5e649e811079)

3. Payslip page, upon clicking the specific item in the Payroll, it will be redirected to its designated Payslip
![2Screenshot_2024-04-17_15-03-47](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/9a6dbde9-cf28-41e5-bb5a-d311c82d8149)

2024-04-17 07:25 UTC, torodeveloper requested changes
The Payslips table is overcrowded. It's hard to read the data in the cells. Can you display only the primary details? Then display the full details in a separate page or modal when clicking on a row.

2024-04-17 07:28 UTC, torodeveloper requested changes
<img width="1024" alt="image" src="https://github.com/torodeveloper/payroll-system-bellini-app/assets/121865290/f16f43c0-9a93-489d-973c-3d08fe4aea3b">

It displays `NaN` after clicking on the next button. It should be disabled if I'm already on the last page.

2024-04-17 07:35 UTC, torodeveloper commented
I noticed the buttons and navigation on your app have a different appearance compared to Alaina's app. Can someone of you create an app theme first then PR it separately?

2024-04-17 07:41 UTC, torodeveloper requested changes
The top navigation links are not working.

2024-04-18 08:22 UTC, kaedm commented
1. update on table, only important items are show
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/a49704c6-4801-4adc-8929-709463efac9b)

2. selected row data is now in modal 

![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/35283291-bb11-471f-8701-af4ea6ea027a)

2024-04-19 02:56 UTC, kaedm commented
1. Only important details are now displayed in the payslips page
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/6a21d041-6470-4e67-91e6-bfa612efd05d)

2. upon clicking the row, modal will open and display all the information of that specific row.
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/60f52ed5-f091-4489-92fe-948d6ac1fd38)

3. Navbar payroll link is now routed to the payroll page, the other links are static given that thay are not existing in this project. Waiting for themes made by alaina before applying.
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/13fc911d-edca-409d-8d8a-0b4163dbb921)

2024-04-22 07:23 UTC, kaedm commented
1. Currently working on the deduction page
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/ff50a701-c368-472e-86e3-ec6beff9c736)

2. Made the Create deduction modal 
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/63d587b5-c076-43c9-9ba5-e4553f499363)

2024-04-23 03:35 UTC, torodeveloper commented
Can you rebase this to the latest master branch and resolve the conflicts?

2024-04-24 02:56 UTC, torodeveloper requested changes

2024-04-24 02:56 UTC, torodeveloper commented on pages/deduction.json
This page should not be included in this PR.

2024-04-24 02:56 UTC, torodeveloper commented on components/create-deduction/index.json
This modal should not be included in this PR.

2024-04-24 02:56 UTC, torodeveloper commented on components/navigation/index.json
We already have a navigation-bar component, do we still need this one?

2024-04-24 08:07 UTC, kaedm commented
1. Pagination on deduction page
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/d98399d3-1f6a-46dd-ac07-bf37dbb22d00)

1. Pagination on Payroll and Payslips page
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/3114fb94-9223-4b8b-a98c-16870e98d986)

2024-04-25 05:35 UTC, torodeveloper requested changes

2024-04-25 05:35 UTC, torodeveloper commented on stylesheets/style.css
> +.input-content{
Need to format it correctly:

```suggestion
.data-container {
    display: flex;
    width: 100%;
    justify-content:space-between;
}

.data-card {
    background-color: #DEF2F1;
    margin: 1rem;
    padding: .5rem 2rem;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: .5rem;
}   

.table-container {
    position: relative;
}

.spinner {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

table {
    height: 100%;
}

.eHeader div {
    width: 100%;
    display: flex;
    justify-content: space-between;
}

.payslip-container {
    display: flex;
}

.payslip-container ul {
    display: flex;
    flex-direction: column;
}

.eHeader div {
    height: 100%;
    display: flex;
    align-items: center;
}

.eHeader div span {
    height: 100%;
    display: flex;
    align-items: center;
}

.input-content {
```

2024-04-25 05:35 UTC, torodeveloper commented on app.json
> +  "name": "payroll-system_1",
```suggestion
  "name": "payroll-system",
```

2024-04-25 05:43 UTC, kaedm commented on stylesheets/style.css
> +.input-content{
.data-container{
    display: flex;
    width: 100%;
    justify-content:space-between;
}

.data-card{
    background-color: #DEF2F1;
    margin: 1rem;
    padding: .5rem 2rem;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: .5rem;
}   

.table-container{
    position: relative;
}

.spinner {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

table{
    height: 100%;
}

.eHeader div{
    width: 100%;
    display: flex;
    justify-content: space-between;
}

.payslip-container{
    display: flex;
}

.payslip-container ul{
    display: flex;
    flex-direction: column;
}

.eHeader div{
    height: 100%;
    display: flex;
    align-items: center;
}

.eHeader div span{
    height: 100%;
    display: flex;
    align-items: center;
}

.input-content{
    display: flex;
    flex-direction: column;
} 
is this correct?

2024-04-25 06:22 UTC, torodeveloper submitted a review, later dismissed

2024-04-25 07:45 UTC, torodeveloper approved these changes

2024-04-25 07:45 UTC, merged