Deduction page
torodeveloper/payroll-system-bellini-app pull request #6
Opened 2024-04-23 06:31 UTC by kaedm

deduction page with create deduction modal

2024-04-23 06:56 UTC, kaedm commented
1. Deduction page
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/c04de212-f3e5-4b5b-a689-ce299c9490d3)

2. Create deduction modal
3. 
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/ec7c0c8c-51ec-4903-92f3-1cad2ec61ece)

2024-04-26 00:42 UTC, torodeveloper requested changes

2024-04-26 00:42 UTC, torodeveloper commented on app.json
> +  "defaultPage": "benefits",
I thought payroll would be our default page. Why did you change it to benefits?

2024-04-26 00:42 UTC, torodeveloper commented on components/navigation/index.json
The navigation-bar component is deleted again and this component is added again.

2024-04-26 00:42 UTC, torodeveloper commented on components/run-payroll/index.json
You can't remove this run-payroll modal.

2024-04-26 00:42 UTC, torodeveloper commented on components/run-payslips/index.json
You can't remove this run-payslips modal.

2024-04-26 00:42 UTC, torodeveloper commented on pages/payslips.json
You can't remove this payslips page.

2024-04-26 01:56 UTC, torodeveloper commented on app.json
> +  "name": "payroll-system_1",
```suggestion
  "name": "payroll-system",
```

2024-04-26 02:31 UTC, torodeveloper commented on components/new-role/stylesheets/new-role.css
> +.small-input {
Shouldn't it be?
```suggestion
new-role .small-input {
```

2024-04-26 02:32 UTC, torodeveloper commented on components/new-role/stylesheets/new-role.css
> +new-role {
Please remove empty css declaration.

2024-04-26 02:38 UTC, kaedm commented on components/new-role/stylesheets/new-role.css
> +new-role {
![image](https://github.com/torodeveloper/payroll-system-bellini-app/assets/165970120/e940cd07-0da3-4cb2-b96e-381f4052a8dd)

2024-04-26 05:16 UTC, torodeveloper approved these changes

2024-04-26 05:16 UTC, merged